spring:
  datasource:
    url: jdbc:mysql://localhost:3306/evaluaciones
    username: root
    password: '@RM.2023'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false
